# Generated by Django 4.2.6 on 2023-11-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0002_rename_nurseid_ward_assignednurseid_ward_isassigned"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugId", models.PositiveIntegerField()),
                ("drugName", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recordId", models.PositiveIntegerField()),
                ("doctorId", models.PositiveIntegerField()),
                ("patientId", models.PositiveIntegerField()),
                ("disease", models.CharField(max_length=30)),
                ("appointmentDate", models.DateField(auto_now=True)),
            ],
        ),
    ]
