# Generated by Django 4.2.6 on 2023-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0003_pharmacy_treatmentrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatmentrecord",
            name="id",
        ),
        migrations.RemoveField(
            model_name="treatmentrecord",
            name="recordId",
        ),
        migrations.AddField(
            model_name="treatmentrecord",
            name="treatment_record_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
