# Generated by Django 4.2.6 on 2023-11-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0004_remove_treatmentrecord_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ward",
            name="id",
        ),
        migrations.AlterField(
            model_name="ward",
            name="WardId",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ward",
            name="WardType",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Operation room", "Operation room"),
                    ("ICU", "ICU"),
                ],
                default="Normal",
                max_length=30,
            ),
        ),
    ]
