# Generated by Django 4.2.6 on 2023-11-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0005_remove_ward_id_alter_ward_wardid_alter_ward_wardtype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Nurse",
        ),
        migrations.DeleteModel(
            name="PatientDischargeDetails",
        ),
        migrations.DeleteModel(
            name="Pharmacy",
        ),
        migrations.DeleteModel(
            name="TreatmentRecord",
        ),
        migrations.DeleteModel(
            name="Ward",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="department",
        ),
    ]
