# Generated by Django 4.2.6 on 2023-11-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0006_delete_appointment_delete_nurse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assignedDoctorId",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="wardId",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
