# Generated by Django 4.2.6 on 2023-11-22 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("phtrs", "0007_remove_patient_assigneddoctorid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patient",
            new_name="Citizen",
        ),
        migrations.RenameModel(
            old_name="Doctor",
            new_name="Worker",
        ),
    ]
