# Generated by Django 4.2.6 on 2023-11-26 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phtrs", "0008_rename_patient_citizen_rename_doctor_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=30)),
                (
                    "size",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[("center", "center"), ("roadside", "roadside")],
                        max_length=30,
                    ),
                ),
                ("area", models.CharField(max_length=30)),
                ("priority", models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
